### ISSUE TITLE
Seller name and Seller URL are blank on thousands of rows

### ISSUE THREAD

**Issue by mfr415** [epctex/etsy-scraper#2]
I am on the trial of using this actor and running into two critical issues:

1. I loaded 2500 rows to see how good the data is.  Out of 2500, over 1400 rows have blank values for seller name and seller URL.  See my screenshot

2. 
![blank](https://user-images.githubusercontent.com/73190503/226540273-c9841541-d7f3-489b-aeba-24a28dae7c3e.jpg)
It also seems the "listed on" field value is not accurate at all.  I looked a few listings, but in apify, one of the listings says "Listed on" equal to yesterday, but this is not possible as this product has tons of reviews and sales.  Other tools I am using to compare data show this product was listed 10 months ago.

**Comment by tugkan** [comment]
Hey @mfr415 !

Thank you very much for reporting. We also got informed by our automated tests regarding this issue. We raised a fix about the seller name and seller URL and all should be fine now. You can use the latest version. About the "Listed On" field, we only use the data shown on Etsy at the bottom of the page. But I totally get your point. The same problem happens with this [listing](https://www.etsy.com/listing/992091115/rug-antique-turkish-rug-oriental-rug?click_key=afd3af6324f3ba5d601b199c156ec15b6ac2bab1%3A992091115&click_sum=3c686d91&ref=shop_home_recs_36&pro=1&frs=1) as well. So possibly, Etsy has a different logic behind this but the actor only retrieves the results on a real-time basis.

Please let us know if there is anything that we can help you with.
Best
